name: 'Run KBC configs'
description: 'Run KBC configs in parallel and verify that all were successful.'
author: 'Keboola'
inputs:
  host:
    description: 'Storage API host.'
    required: false
    default: 'connection.keboola.com'
  token:
    description: 'Storage API token.'
    required: true
  componentId:
    description: 'Component ID.'
    required: true
  tag:
    description: 'Component tag to run.'
    required: true
  configs:
    description: 'Space separated list of the config IDs.'
    required: true
  timeout:
    description: 'How long to wait for the job to finish. Specified as a sequence of decimal numbers with unit suffixes.'
    required: false
    default: '5m'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.token }}
    - ${{ inputs.componentId }}
    - ${{ inputs.tag }}
    - ${{ inputs.timeout }}
    - ${{ inputs.configs }}
